name: Deploy to ICS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ics
        chmod 600 ~/.ssh/id_ics
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ics

    - name: Deploy via SSH
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" << 'EOF'
          cd ICSYAK
          git pull
          cd ..

          JOBID=$(squeue -u yousefk | awk 'NR==2 {print $1}')

          if [[ ! -z "$JOBID" ]]; then
            echo "Canceling job $JOBID"
            scancel "$JOBID"
          else
            echo "No job to cancel"
          fi

          echo "Starting new job..."
          srunfile run_main.sh
        EOF