name: Deploy to ICS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key and config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ics
          chmod 600 ~/.ssh/id_ics

          echo "Host ics" >> ~/.ssh/config
          echo "  HostName ${{ secrets.SSH_HOST }}" >> ~/.ssh/config
          echo "  User ${{ secrets.SSH_USER }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_ics" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ics

      - name: List loaded SSH keys (debug)
        run: ssh-add -l

      - name: Debug SSH connection (dry run)
        run: ssh -vvv ics true

      - name: Deploy to Openlab
        run: |
          ssh ics << 'EOF'
            cd ICSYAK
            git pull
            cd ..

            JOBID=$(squeue -u yousefk | awk 'NR==2 {print $1}')
            if [[ ! -z "$JOBID" ]]; then
              echo "Canceling job $JOBID"
              scancel "$JOBID"
            else
              echo "No job to cancel"
            fi

            echo "Starting new job..."
            srunfile run_main.sh
          EOF